server:
  port: 8088

spring:
  redis:
    database: 0
    port: 6379
    host: 192.168.211.110
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.211.110:3306/ylang_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

keypair:
  resource: kaikeba.jks
  password: kaikeba
  alias: kaikeba
