server:
  port: 9301
spring:
  application:
    name: kkb-monitor
  security:
    user:
      name: kkb
      password: 123456

  boot:  # 不显示admin-server的监控信息
    admin:
      discovery:
        ignored-services: ${spring.application.name}

