spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info
    com.kkb.projectsearch: debug
logstash:
  host: localhost