server:
  port: 8087
spring:
  application:
    name: kkb-portal
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://8.140.125.207:3306/kkb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: kkb
#    password: kkb
    url: jdbc:mysql://175.24.60.137:3306/lyl_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: kkbtest
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
  servlet:
    multipart:
      enabled: true  #开启文件上传
      max-request-size: 10MB #限制文件上传大小为10M
#  flyway:
#    # 启用Flyway功能
#    enabled: true
#    # 禁用Flyway的clean命令，使用clean命令会删除schema下的所有表
#    clean-disabled: true
#    # 设置Flyway的SQL脚本路径
#    locations: classpath:db/migration
#    # 设置版本信息控制表名称，默认flyway_schema_history
#    table: flyway_schema_history
#    # 在执行migrate命令时需要有flyway_schema_history表，通过baseline命令可以生成该表
#    baseline-on-migrate: true
#    # 指定baseline版本号，低于该版本的SQL脚本在migrate是不会执行
#    baseline-version: 1
#    # 设置字符编码
#    encoding: UTF-8
#    # 不允许不按顺序迁移
#    out-of-order: false
#    # 设置Flyway管控的schema，不设置的话为datasourcel.url中指定的schema
#    schemas: kkb
#    # 执行migrate时开启校验
#    validate-on-migrate: true
#    url: jdbc:mysql://8.140.125.207:3306/kkb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    user: kkb
#    password: kkb
  redis:
    host: 175.24.60.137 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 3 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 1 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）
mybatis-plus:
  # 支持统配符 * 或者 ; 分割
  typeEnumsPackage: com.kkb.project.domain.enums
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.kkb.project.portal.domain
logging:
  level:
    root: info
    com.kkb.project.dao: debug
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）
#MinIO对象存储相关配置
minio:
  endpoint: http://175.24.60.137:9000 #MinIO服务所在地址
  bucketName: kkb #存储桶名称
  accessKey: admin #访问的key
  secretKey: admin123 #访问的秘钥
# oauth2相关配置
security:
  oauth2:
    # 客户端配置
    client:
      access-token-uri: http://localhost:8088/oauth/token # 令牌申请端点
      client-id: kkb
      client-secret: secret
      grant-type: password
      scope: all
