spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kkb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    root: info
    com.kkb.projectdemo: debug
logstash:
  host: localhost