spring:
  datasource:
    url: jdbc:mysql://db:3306/kkb?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  file:
    path: /var/logs
  level:
    root: info
    com.kkb.projectdemo: info
logstash:
  host: logstash