apiVersion: v1
kind: Service
metadata:
  name: kkb-portal-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: kkb-portal
  ports:
    - name: http
      protocol: TCP
      port: 8085
      targetPort: 8085