apiVersion: apps/v1
kind: Deployment
metadata:
  name: kkb-auth-deployment
  namespace: default
  labels:
    app: kkb-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kkb-auth
  template:
    metadata:
      labels:
        app: kkb-auth
    spec:
      containers:
        - name: kkb-auth
          # 指定Docker Hub中的镜像地址
          image: macrodocker/kkb-auth:1.0-SNAPSHOT
          ports:
            - containerPort: 8401
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            # 指定Nacos地址
            - name: spring.cloud.nacos.discovery.server-addr
              value: http://192.168.3.101:8848
            - name: spring.cloud.nacos.config.server-addr
              value: http://192.168.3.101:8848
          volumeMounts:
            - mountPath: /var/logs
              name: log-volume
      volumes:
        - name: log-volume
          hostPath:
            path: /mydata/app/kkb-auth/logs
            type: DirectoryOrCreate