apiVersion: v1
kind: Service
metadata:
  name: kkb-admin-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: kkb-admin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080